### ISSUE TITLE
Generate manifests during Registerung Node Workflow

### ISSUE THREAD

**Issue by matmah** [edgefarm/backstage-workflows#20]
Replace NODENAME with concrete nodename

```yaml
apiVersion: v1
kind: Node
metadata:
  labels:
    kubernetes.io/hostname: NODENAME
    openyurt.io/is-edge-worker: "true"
    apps.openyurt.io/desired-nodepool: NODENAME
  name: NODENAME
spec:
  taints:
  - effect: NoSchedule
    key: edgefarm.io
---
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: NODENAME
spec:
  selector:
    matchLabels:
      apps.openyurt.io/nodepool: NODENAME
  type: Edge
```
